name: HelpDemo
version: 1.0
main: com.ryanmichela.helpdemo.HelpPlugin

commands:
  foo:
    description: Prints FOO to the screen.
    usage: <command>
    permission: help.foo

  bar:
    aliases: [bar2, bar3, bar4]

  baz:
    description: The baz command